### ISSUE TITLE
Mimicking org-mode

### ISSUE THREAD

**Issue by dangom** [rougier/mu4e-thread-folding#1]
Really nice package, as always.
Would be cool if the keybindings would follow org mode outline commands, such as tab and S-tab for cycling visibility.
I guess all that is needed is a "toggle/dwim" function that looks at the current state of a thread and switches it, I suppose. I don't know much about overlays - would that be easy to implement? I could try a PR if that's the case.

**Comment by rougier** [comment]
I did not  find an easy solution. I think you need to store the state of the folding in the overlay (you can add any property) and toggle this property on the master thread (or the children?).

**Comment by guibor** [comment]
+1 on this feature request. I have a hacky setup that uses some function someone wrote that works, this package seems much better if it supported the ability to toggle visibility.

**Comment by rougier** [comment]
I think this is doable for a single thread (tab) but I'm not sure of the behavior for all thread at once (shift+tab):

1. Fold or unfold them based on the folding status of the thread under cursor (meaning they're all folded or unfolded at once)
2. Fold / unfold each thread based on their current folding status.

Thoughts ?

**Comment by guibor** [comment]
I think two options (personal thoughts of course)
1 - no need to support at all for all threads (I don't see the use)
2 - or toggle between all folded and all unfolded, with by default if the states are mixed you go to all unfolded (unless they are all unfolded already). Isn't this what happens in org-mode?

**Comment by rougier** [comment]
I think you're right, option 1 would be enough (and probably simpler to implement)

**Comment by mankoff** [comment]
I'd also suggest the same key can cycle states.

Press cycle key:
+ If on thread
  + If thread closed: open
  + If thread open:
    + If any other thread closed: open all
    + If all threads open: close all
+ If not on thread
   + If any closed: open all
   + If all open: close all

**Comment by rougier** [comment]
I've just implemented the single thread.

**Comment by rougier** [comment]
@mankoff Your proposal might be more difficult to implement because I do not have a global view on all thread (or it would require two passes)
