### ISSUE TITLE
Error if not in threaded view

### ISSUE THREAD

**Issue by mankoff** [rougier/mu4e-thread-folding#17]
```
error in process filter: mu4e-error: [mu4e] No thread info found
error in process filter: [mu4e] No thread info found
```

If I turn of threaded view (i.e. `P` key or `(mu4e-headers-toggle-threading)`)

**Comment by rougier** [comment]
Do you use the last version? I think there PR #16 was supposed to address this.

**Comment by mankoff** [comment]
Sorry. Stale code on my end. Thanks!
