### ISSUE TITLE
Also fold unread messages

### ISSUE THREAD

**Issue by mscastanho** [rougier/mu4e-thread-folding#22]
I've been using mu4e-thread-folding for a few weeks and it is really useful, thanks!

However, I'd really like to be able to also fold unread messages in a thread. I follow many mailing lists so having very long threads with many unread e-mails is very common. In such cases, since unread messages are not folded, the benefit provided by the package goes away.

Something like what Mozilla Thunderbird does would be very useful: when you fold a thread that has unread messages, it modifies the "face" of the thread root header to `not bold` + `underlined` (and the child messages are folded).

How hard would it be to implement that?

**Comment by rougier** [comment]
It was what I intended to do in the first place but I remember I did not really manage. I can try to give another try. I'll leave the issue open in the meantime.

**Comment by theottm** [comment]
I would also enjoy having this feature !

**Comment by theottm** [comment]
Added a PR #28

**Comment by rougier** [comment]
Thread folding has been integrated in mu4e. It is a different implementation that is less lfeixble but much faster.

**Comment by tareefdev** [comment]
Could you refer to the actual function/variable to use built-in thread folding in recent mu4e versions?

**Comment by rougier** [comment]
It is here: https://github.com/djcb/mu/blob/master/mu4e/mu4e-thread.el
Just activate `mu4e-thread-mode` and you should get the bindings.

**Comment by tareefdev** [comment]
I see! It's not included in the latest 1.10.8 release. Thank you!
