### ISSUE TITLE
Alignment is off for some reason?

### ISSUE THREAD

**Issue by apc** [rougier/mu4e-thread-folding#30]
When I enable `mu4e-thread-folding-mode`, the buffer alignment goes out of whack: 

<img width="290" alt="image" src="https://github.com/rougier/mu4e-thread-folding/assets/350504/cece8cc5-1654-4e5c-b45f-d9c0a26f19ec">

<img width="337" alt="image" src="https://github.com/rougier/mu4e-thread-folding/assets/350504/bad2e715-997e-4bb9-b7f9-66da844ba9f6">

Here's my config: 

```elisp
(use-package mu4e-thread-folding
  :after mu4e
  :straight (:type git :host github :repo "rougier/mu4e-thread-folding")
  :init
  (add-to-list 'mu4e-header-info-custom
               '(:empty . (:name "Empty"
                           :shortname ""
                           :function (lambda (msg) "  "))))
  :custom
  (mu4e-headers-fields '((:empty         .    2)
                         (:human-date    .   12)
                         (:flags         .    6)
                         (:mailing-list  .   10)
                         (:from          .   22)
                         (:subject       .   nil)))
    :bind (:map mu4e-headers-mode-map
              ("<tab>"     . mu4e-headers-toggle-at-point)
              ("<left>"    . mu4e-headers-fold-at-point)
              ("<S-left>"  . mu4e-headers-fold-all)
              ("<right>"   . mu4e-headers-unfold-at-point)
              ("<S-right>" . mu4e-headers-unfold-all)))
```

Any hints on what could be causing this?

**Comment by rougier** [comment]
There's is  a new package [mu4e-thread](https://github.com/rougier/mu4e-thread) that has been merged into mu4e that might solve the problem. It is a bit different but it is supposed to be much faster.

**Comment by apc** [comment]
Thanks and thanks for all the work you do!

I'll sit and wait for now: I install `mu` with Homebrew and what I get that way doesn't yet have `mu4e-thread.el` in it. I've managed with patching together something using your own `mu4e-folding.el` which I suspect is an earlier version of what ended up being merged into mu4e?

**Comment by rougier** [comment]
What has been merged is [here](https://github.com/djcb/mu/blob/master/mu4e/mu4e-thread.el)
