### ISSUE TITLE
Quelpa support

### ISSUE THREAD

**Issue by FrostyX** [rougier/mu4e-thread-folding#5]
I am trying to install this package using quelpa 

    (use-package mu4e-thread-folding 
      :quelpa (mu4e-thread-folding :fetcher github :repo "rougier/mu4e-thread-folding"))

and getting the following error

    Error getting PACKAGE-DESC: (error Package lacks a file header)
    quelpa-package-install: Wrong type argument: package-desc, nil

**Comment by rougier** [comment]
Thanks for the report. Last commit should have fixed it.

**Comment by FrostyX** [comment]
Thank you, I can confirm it fixed it.
