### ISSUE TITLE
Allow setting default view to open rather than closed

### ISSUE THREAD

**Issue by mankoff** [rougier/mu4e-thread-folding#6]

**Comment by mankoff** [comment]
But also +1 nice package. Thank you.

**Comment by rougier** [comment]
If you provide the name of the option, I can do it!

**Comment by mankoff** [comment]
`mu4e-thread-folding-default-view` to `'expanded` or `'collapsed` ? Or `mu4e-thread-folding-default-collapsed` to `t` or `nil`?

**Comment by rougier** [comment]
Thanks, I'll implement it using `mu4e-thread-folding-default-view`

**Comment by rougier** [comment]
Done.
