### ISSUE TITLE
Re-indent and delete trailing whitespace?

### ISSUE THREAD

**Issue by phil-s** [rougier/mu4e-thread-folding#8]
Emacs Lisp has very standard indentation, based on what Emacs does by default, so it would make contributions easier if you could `C-x h TAB` (or otherwise `indent-region` for the whole buffer) and you might consider `M-x delete-trailing-whitespace` too (using https://github.com/lewang/ws-butler is a great way to avoid introducing those).

(Or if this is using some custom indentation rules, you should configure those with file-local variables so that other people will also be using them.)

Regardless, it's a great feature!  I hope to see it contributed to mu4e!

**Comment by rougier** [comment]
Thanks, just re-indented everything.
